*** Starting uWSGI 2.0.19.1 (64bit) on [Tue May 18 09:42:14 2021] ***
compiled with version: 9.3.0 on 13 May 2021 02:53:04
os: Linux-5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
nodename: iZg9h0nphx5ec7Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/code
detected binary path: /root/.virtualenvs/test_env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7723
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
The -s/--socket option is missing and stdin is not a socket.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue May 18 14:11:11 2021] ***
compiled with version: 9.3.0 on 13 May 2021 02:53:04
os: Linux-5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
nodename: iZg9h0nphx5ec7Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/code/
your processes number limit is 7723
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33169 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
PEP 405 virtualenv detected: /root/.virtualenvs/test_env
Set PythonHome to /root/.virtualenvs/test_env
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55beec6810c0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55beec6810c0 pid: 17619 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17619)
spawned uWSGI worker 1 (pid: 17623, cores: 1)
spawned uWSGI http 1 (pid: 17624)
[pid: 17623|app: 0|req: 1/1] 211.71.91.194 () {38 vars in 715 bytes} [Tue May 18 14:11:28 2021] GET / => generated 97317 bytes in 113 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 2/2] 211.71.91.194 () {40 vars in 802 bytes} [Tue May 18 14:11:29 2021] GET /shop_list_new/%25null%25 => generated 46894 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 3/3] 211.71.91.194 () {38 vars in 700 bytes} [Tue May 18 14:11:30 2021] GET /static/assets/css/bootstrap.min.css => generated 120979 bytes in 4 msecs via sendfile() (HTTP/1.1 200) 8 headers in 310 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 4/4] 211.71.91.194 () {46 vars in 806 bytes} [Tue May 18 14:11:30 2021] POST /search_flower => generated 69974 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 74 bytes (2 switches on core 0)
[pid: 17623|app: 0|req: 5/5] 211.71.91.194 () {42 vars in 830 bytes} [Tue May 18 14:11:30 2021] GET /static/assets/fonts/fontawesome-webfont.woff2?v=4.7.0 => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 211 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 6/6] 211.71.91.194 () {40 vars in 827 bytes} [Tue May 18 14:11:30 2021] GET /static/uploaded_AVATAR/Dried%20Rhododendron_1.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 212 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 7/7] 211.71.91.194 () {40 vars in 835 bytes} [Tue May 18 14:11:30 2021] GET /static/uploaded_AVATAR/Dried%20Eucalyptus%20leaf_1.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 212 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 8/8] 211.71.91.194 () {40 vars in 819 bytes} [Tue May 18 14:11:30 2021] GET /static/uploaded_AVATAR/Dried%20Lavender_1.jpg => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 213 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 9/9] 211.71.91.194 () {40 vars in 815 bytes} [Tue May 18 14:11:30 2021] GET /static/uploaded_AVATAR/Ceramic%20Vase_1.jpg => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 212 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 10/10] 211.71.91.194 () {40 vars in 739 bytes} [Tue May 18 14:15:24 2021] GET / => generated 97317 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 11/11] 211.71.91.194 () {40 vars in 768 bytes} [Tue May 18 14:15:26 2021] GET /about => generated 14600 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 12/12] 211.71.91.194 () {38 vars in 721 bytes} [Tue May 18 14:15:26 2021] GET /static/images/about/shop_pic.jpg => generated 152892 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 298 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 13/13] 211.71.91.194 () {38 vars in 721 bytes} [Tue May 18 14:15:26 2021] GET /static/images/about/countity.png => generated 137728 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 14/14] 211.71.91.194 () {38 vars in 713 bytes} [Tue May 18 14:15:26 2021] GET /static/images/about/team.png => generated 125912 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 15/15] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:15:26 2021] GET /static/images/about/deliver.png => generated 124298 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 16/16] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:15:26 2021] GET /static/images/about/service.png => generated 111675 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 17/17] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:15:26 2021] GET /static/images/brand/brand-1.jpg => generated 5606 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 18/18] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:15:28 2021] GET /static/images/brand/brand-2.jpg => generated 5504 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (0 switches on core 0)
[uwsgi-http key: 39.107.247.224:5000 client_addr: 211.71.91.194 client_port: 60632] hr_write(): Broken pipe [plugins/http/http.c line 565]
[uwsgi-http key: 39.107.247.224:5000 client_addr: 211.71.91.194 client_port: 59864] hr_write(): Broken pipe [plugins/http/http.c line 565]
[pid: 17623|app: 0|req: 19/19] 211.71.91.194 () {40 vars in 738 bytes} [Tue May 18 14:21:06 2021] GET / => generated 97317 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17623|app: 0|req: 20/20] 211.71.91.194 () {40 vars in 765 bytes} [Tue May 18 14:21:08 2021] GET /blog => generated 0 bytes in 35 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17623|app: 0|req: 21/21] 211.71.91.194 () {40 vars in 765 bytes} [Tue May 18 14:21:09 2021] GET /blog => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17623|app: 0|req: 22/22] 211.71.91.194 () {42 vars in 796 bytes} [Tue May 18 14:21:10 2021] GET /blog => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 23/23] 47.101.32.174 () {30 vars in 410 bytes} [Tue May 18 14:22:16 2021] GET / => generated 97317 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 24/24] 47.101.32.174 () {30 vars in 504 bytes} [Tue May 18 14:22:17 2021] GET /static/images/shipping-icon/Made-By-Artists.png => generated 4964 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 292 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 25/25] 47.101.32.174 () {30 vars in 492 bytes} [Tue May 18 14:22:17 2021] GET /static/images/shipping-icon/Freshness.png => generated 4393 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 292 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 26/26] 47.101.32.174 () {30 vars in 476 bytes} [Tue May 18 14:22:17 2021] GET /static/images/logo/logo-white.png => generated 74812 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 27/27] 47.101.32.174 () {30 vars in 464 bytes} [Tue May 18 14:22:17 2021] GET /static/images/logo/logo.png => generated 36916 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 28/28] 47.101.32.174 () {30 vars in 500 bytes} [Tue May 18 14:22:17 2021] GET /static/images/shipping-icon/Free-Delivery.png => generated 4194 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 292 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 29/29] 47.101.32.174 () {30 vars in 498 bytes} [Tue May 18 14:22:17 2021] GET /static/images/shipping-icon/Online-Order.png => generated 4091 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 292 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 30/30] 47.101.32.174 () {30 vars in 460 bytes} [Tue May 18 14:22:17 2021] GET /static/images/payment.png => generated 5352 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 291 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 31/31] 47.101.32.174 () {30 vars in 458 bytes} [Tue May 18 14:22:18 2021] GET /static/images/switch.png => generated 1151 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 290 bytes (0 switches on core 0)
[pid: 17623|app: 0|req: 32/32] 47.101.32.174 () {30 vars in 476 bytes} [Tue May 18 14:22:18 2021] GET /static/uploaded_AVATAR/Aloe_1.jpg => generated 61670 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (0 switches on core 0)
Tue May 18 14:23:25 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue May 18 14:23:51 2021] ***
compiled with version: 9.3.0 on 13 May 2021 02:53:04
os: Linux-5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
nodename: iZg9h0nphx5ec7Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/code/
your processes number limit is 7723
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44343 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
PEP 405 virtualenv detected: /root/.virtualenvs/test_env
Set PythonHome to /root/.virtualenvs/test_env
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562980a98440
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x562980a98440 pid: 17824 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17824)
spawned uWSGI worker 1 (pid: 17826, cores: 1)
spawned uWSGI http 1 (pid: 17827)
[pid: 17826|app: 0|req: 1/1] 211.71.91.194 () {40 vars in 739 bytes} [Tue May 18 14:24:20 2021] GET / => generated 97317 bytes in 135 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17826|app: 0|req: 2/2] 211.71.91.194 () {40 vars in 766 bytes} [Tue May 18 14:24:26 2021] GET /blog => generated 0 bytes in 32 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17826|app: 0|req: 3/3] 211.71.91.194 () {40 vars in 766 bytes} [Tue May 18 14:24:27 2021] GET /blog => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17826|app: 0|req: 4/4] 211.71.91.194 () {40 vars in 766 bytes} [Tue May 18 14:24:27 2021] GET /blog => generated 0 bytes in 9 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/main/views.py", line 488, in blog
    return render_template('blog/index.html', post1=post1, posts=posts, latest_posts=latest_posts)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/.virtualenvs/test_env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/code/app/templates/blog/index.html", line 64, in top-level template code
    {% if not current_user.is_liking(post1) %}
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_liking'
[pid: 17826|app: 0|req: 5/5] 211.71.91.194 () {42 vars in 797 bytes} [Tue May 18 14:24:28 2021] GET /blog => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 17826|app: 0|req: 6/6] 211.71.91.194 () {38 vars in 715 bytes} [Tue May 18 14:28:27 2021] GET / => generated 97317 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 7/7] 211.71.91.194 () {40 vars in 768 bytes} [Tue May 18 14:28:28 2021] GET /about => generated 14600 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 8/8] 211.71.91.194 () {40 vars in 773 bytes} [Tue May 18 14:28:30 2021] GET /about => generated 14600 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 9/9] 211.71.91.194 () {42 vars in 801 bytes} [Tue May 18 14:28:30 2021] GET /static/images/about/team.png => generated 1 bytes in 4 msecs (HTTP/1.1 206) 9 headers in 348 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 10/10] 211.71.91.194 () {42 vars in 807 bytes} [Tue May 18 14:28:30 2021] GET /static/images/about/shop_pic.jpg => generated 1 bytes in 0 msecs (HTTP/1.1 206) 9 headers in 347 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 11/11] 211.71.91.194 () {42 vars in 809 bytes} [Tue May 18 14:28:30 2021] GET /static/images/about/countity.png => generated 1 bytes in 1 msecs (HTTP/1.1 206) 9 headers in 348 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 12/12] 211.71.91.194 () {42 vars in 805 bytes} [Tue May 18 14:28:30 2021] GET /static/images/about/service.png => generated 1 bytes in 0 msecs (HTTP/1.1 206) 9 headers in 346 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 13/13] 211.71.91.194 () {42 vars in 805 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/deliver.png => generated 1 bytes in 0 msecs (HTTP/1.1 206) 9 headers in 346 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 14/14] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:28:31 2021] GET /static/images/brand/brand-2.jpg => generated 5504 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (0 switches on core 0)
[pid: 17826|app: 0|req: 15/15] 211.71.91.194 () {42 vars in 801 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/team.png => generated 7652 bytes in 2 msecs (HTTP/1.1 206) 9 headers in 351 bytes (47 switches on core 0)
[pid: 17826|app: 0|req: 16/16] 211.71.91.194 () {42 vars in 806 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/deliver.png => generated 83418 bytes in 2 msecs (HTTP/1.1 206) 9 headers in 351 bytes (328 switches on core 0)
[pid: 17826|app: 0|req: 17/17] 211.71.91.194 () {42 vars in 809 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/countity.png => generated 31148 bytes in 3 msecs (HTTP/1.1 206) 9 headers in 352 bytes (154 switches on core 0)
[pid: 17826|app: 0|req: 18/18] 211.71.91.194 () {42 vars in 808 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/shop_pic.jpg => generated 85732 bytes in 2 msecs (HTTP/1.1 206) 9 headers in 352 bytes (307 switches on core 0)
[pid: 17826|app: 0|req: 19/19] 211.71.91.194 () {42 vars in 806 bytes} [Tue May 18 14:28:31 2021] GET /static/images/about/service.png => generated 44515 bytes in 2 msecs (HTTP/1.1 206) 9 headers in 351 bytes (195 switches on core 0)
[pid: 17826|app: 0|req: 20/20] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:28:31 2021] GET /static/images/brand/brand-3.jpg => generated 5526 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (0 switches on core 0)
[pid: 17826|app: 0|req: 21/21] 211.71.91.194 () {38 vars in 719 bytes} [Tue May 18 14:28:31 2021] GET /static/images/brand/brand-4.jpg => generated 5390 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (0 switches on core 0)
[pid: 17826|app: 0|req: 22/22] 211.71.91.194 () {40 vars in 807 bytes} [Tue May 18 14:28:33 2021] GET /shop_list_new/%25null%25 => generated 46894 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 23/23] 211.71.91.194 () {46 vars in 806 bytes} [Tue May 18 14:28:33 2021] POST /search_flower => generated 69974 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 74 bytes (2 switches on core 0)
[pid: 17826|app: 0|req: 24/24] 211.71.91.194 () {40 vars in 792 bytes} [Tue May 18 14:28:34 2021] GET /index => generated 97317 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 25/25] 211.71.91.194 () {40 vars in 738 bytes} [Tue May 18 14:33:10 2021] GET / => generated 97317 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 26/26] 211.71.91.194 () {40 vars in 801 bytes} [Tue May 18 14:33:12 2021] GET /shop_list_new/%25null%25 => generated 46894 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 27/27] 211.71.91.194 () {46 vars in 805 bytes} [Tue May 18 14:33:12 2021] POST /search_flower => generated 69974 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 74 bytes (2 switches on core 0)
[pid: 17826|app: 0|req: 28/28] 211.71.91.194 () {40 vars in 791 bytes} [Tue May 18 14:33:14 2021] GET /about => generated 14600 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 29/29] 211.71.91.194 () {40 vars in 772 bytes} [Tue May 18 14:33:15 2021] GET /index => generated 97317 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 30/30] 211.71.91.194 () {40 vars in 782 bytes} [Tue May 18 14:33:19 2021] GET /auth/login => generated 15610 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 17826|app: 0|req: 31/31] 211.71.91.194 () {38 vars in 646 bytes} [Tue May 18 14:33:19 2021] GET /static/js/map-script.js => generated 5209 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 305 bytes (0 switches on core 0)
Tue May 18 14:34:20 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
